### ISSUE TITLE
 Could not match user with any stored credentials

### ISSUE THREAD

**Issue by advokatb** [shemanaev/jellyfin-plugin-myshows#2]
Hi.

I've entered my credentials and they're ok.
Some scrobbles were successful but later I get in logs only this:

```
[2023-12-12 18:07:34.367 +02:00] [INF] [218] MyShows: Playback Started
[2023-12-12 18:07:34.368 +02:00] [INF] [218] MyShows: Could not match user with any stored credentials
```

Could this be because I've added users to Jellyfin?

My account is the only admin on the server. And from this account I've entered MyShows credentials.

**Comment by shemanaev** [comment]
Those entries mean that user doesn't have credentials for myshows. It
should not affect other users, that do have connected to service.

ср, 13 дек. 2023 г., 01:21 advokatb ***@***.***>:
